language:
  - node_js
  - version: 8

os:
  - osx
  - linux

cache:
  yarn: true

before_install:
  - nvm install --lts
  - nvm use 'lts/*'
  - npm i -g yarn
  - nvm --version
  - npm --version
  - node --version
  - yarn --version
  - yarn

script:
  - yarn lint
  - yarn nyc

after_success:
  - chmod 0755 /Users/travis/build/l3laze/Steam-Dummy/.nyc_output
  - yarn textcov
  - yarn codecov

notifications:
  email: false
